"""add_asset_class_to_transactions

Revision ID: 360c12315e82
Revises: 1139132c1d1d
Create Date: 2025-12-03 09:20:10.730991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360c12315e82'
down_revision = '1139132c1d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_class', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('asset_class')

    # ### end Alembic commands ###
