"""add_analist_start_date_and_created_at_to_members

Revision ID: 4865223e471f
Revises: d6c12a82413d
Create Date: 2025-11-27 15:07:58.872577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4865223e471f'
down_revision = 'd6c12a82413d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_members')
    op.drop_table('Analist')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    op.create_table('Analist',
    sa.Column('analist_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('analist_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sector', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('analist_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('voting_right', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('analist_id', name=op.f('Analist_pkey'))
    )
    op.create_table('board_members',
    sa.Column('boardmember_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('boardmember_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('voting_right', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('boardmember_id', name=op.f('board_members_pkey'))
    )
    # ### end Alembic commands ###
