"""Add stock price history and company info caching tables

Revision ID: 8f40f0d14d34
Revises: a68a117d05b2
Create Date: 2025-12-10 13:25:57.160914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f40f0d14d34'
down_revision = 'a68a117d05b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_info',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('long_name', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('financial_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_info_ticker'), ['ticker'], unique=True)

    op.create_table('stock_price_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'price_date', name='uq_stock_price_ticker_date')
    )
    with op.batch_alter_table('stock_price_history', schema=None) as batch_op:
        batch_op.create_index('idx_ticker_date', ['ticker', 'price_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_price_history_price_date'), ['price_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_price_history_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_price_history_ticker'))
        batch_op.drop_index(batch_op.f('ix_stock_price_history_price_date'))
        batch_op.drop_index('idx_ticker_date')

    op.drop_table('stock_price_history')
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_info_ticker'))

    op.drop_table('company_info')
    # ### end Alembic commands ###
