"""change_pos_quantity_to_integer_and_rename_pos_amount_to_pos_value

Revision ID: 94df8af42e91
Revises: c9843bb0f7e1
Create Date: 2025-11-27 17:57:57.013179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94df8af42e91'
down_revision = 'c9843bb0f7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_value', sa.Float(), nullable=True))
        batch_op.alter_column('pos_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('pos_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('pos_quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('pos_value')

    # ### end Alembic commands ###
