"""add_missing_transaction_columns

Revision ID: a68a117d05b2
Revises: c62d10569109
Create Date: 2025-12-05 18:36:20.845566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68a117d05b2'
down_revision = 'c62d10569109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_ticker', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transaction_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('transaction_share_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('asset_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('asset_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('asset_type')
        batch_op.drop_column('asset_name')
        batch_op.drop_column('transaction_share_price')
        batch_op.drop_column('transaction_currency')
        batch_op.drop_column('transaction_ticker')
    # ### end Alembic commands ###
