"""Final column fix and initial schema

Revision ID: ac06d6a79fb8
Revises: 
Create Date: 2025-11-21 19:50:27.917418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac06d6a79fb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Analist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analist_id', sa.BigInteger(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('Iv_club', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boardmember_id', sa.BigInteger(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('files_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.BigInteger(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_members_email'), ['email'], unique=True)
        batch_op.drop_column('id')

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.alter_column('portfolio_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('pos_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('voting_proposal', schema=None) as batch_op:
        batch_op.alter_column('proposal_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voting_proposal', schema=None) as batch_op:
        batch_op.alter_column('proposal_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('pos_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.alter_column('portfolio_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False))
        batch_op.drop_index(batch_op.f('ix_members_email'))
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')
        batch_op.drop_column('member_id')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('files_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False))
        batch_op.drop_column('boardmember_id')

    with op.batch_alter_table('Iv_club', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('Analist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False))
        batch_op.drop_column('analist_id')

    # ### end Alembic commands ###
