"""add_file_items_table

Revision ID: c62d10569109
Revises: d00c629cf724
Create Date: 2025-12-05 17:48:01.356928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62d10569109'
down_revision = 'd00c629cf724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_items',
    sa.Column('item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['file_items.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_items')
    # ### end Alembic commands ###
