"""add_pos_ticker_and_pos_sector_to_positions

Revision ID: c9843bb0f7e1
Revises: d6e985de05d3
Create Date: 2025-11-27 17:35:38.103564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9843bb0f7e1'
down_revision = 'd6e985de05d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_ticker', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pos_sector', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('pos_sector')
        batch_op.drop_column('pos_ticker')

    # ### end Alembic commands ###
