"""change_join_date_to_integer_and_remove_analist_start_date

Revision ID: cac5b883a099
Revises: 4865223e471f
Create Date: 2025-11-27 15:55:58.504454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cac5b883a099'
down_revision = '4865223e471f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Wijzig join_date type van TIMESTAMP naar INTEGER met expliciete conversie
    # Gebruik EXTRACT(YEAR FROM ...) om het jaar uit de timestamp te halen
    op.execute("""
        ALTER TABLE members 
        ALTER COLUMN join_date TYPE INTEGER 
        USING EXTRACT(YEAR FROM join_date)::INTEGER
    """)
    
    # Verwijder analist_start_date kolom
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('analist_start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Voeg analist_start_date kolom terug toe
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analist_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    
    # Converteer join_date terug naar TIMESTAMP
    # Converteer integer jaar naar timestamp (1 januari van dat jaar)
    op.execute("""
        ALTER TABLE members 
        ALTER COLUMN join_date TYPE TIMESTAMP WITH TIME ZONE 
        USING (join_date::text || '-01-01')::TIMESTAMP WITH TIME ZONE
    """)

    # ### end Alembic commands ###
