"""Add voting deadline, stock_name and Vote model

Revision ID: d00c629cf724
Revises: 360c12315e82
Create Date: 2025-12-04 16:46:53.906128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00c629cf724'
down_revision = '360c12315e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('vote_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('vote_option', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['voting_proposal.proposal_id'], ),
    sa.PrimaryKeyConstraint('vote_id'),
    sa.UniqueConstraint('proposal_id', 'member_id', name='unique_member_proposal_vote')
    )
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('cash_amount')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_amount', sa.Float(), nullable=True))
        batch_op.drop_column('asset_type')
        batch_op.drop_column('transaction_share_price')
        batch_op.drop_column('transaction_ticker')
        batch_op.drop_column('transaction_currency')

    with op.batch_alter_table('voting_proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voting_proposal', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('deadline')
        batch_op.drop_column('stock_name')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_currency', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_ticker', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_share_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('asset_type', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('transaction_amount')

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    op.drop_table('votes')
    # ### end Alembic commands ###
