"""Add portfolio_id foreign key to positions

Revision ID: d6c12a82413d
Revises: 
Create Date: 2025-11-26 10:15:09.512338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text as sa_text


# revision identifiers, used by Alembic.
revision = 'd6c12a82413d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Controleer of de tabel al data bevat
    connection = op.get_bind()
    result = connection.execute(sa_text("SELECT COUNT(*) FROM positions"))
    row_count = result.scalar()
    
    if row_count > 0:
        # Als er al data is: voeg kolom toe als nullable eerst
        with op.batch_alter_table('positions', schema=None) as batch_op:
            batch_op.add_column(sa.Column('portfolio_id', sa.BigInteger(), nullable=True))
        
        # Update bestaande rijen met een default portfolio_id
        # PAS DIT AAN: vervang 1 door een bestaand portfolio_id, of maak eerst een portfolio aan
        # op.execute("UPDATE positions SET portfolio_id = 1 WHERE portfolio_id IS NULL")
        
        # Maak de kolom NOT NULL (uncomment nadat je de UPDATE hierboven hebt uitgevoerd)
        # with op.batch_alter_table('positions', schema=None) as batch_op:
        #     batch_op.alter_column('portfolio_id', nullable=False)
    else:
        # Als de tabel leeg is: voeg kolom direct toe als NOT NULL
        with op.batch_alter_table('positions', schema=None) as batch_op:
            batch_op.add_column(sa.Column('portfolio_id', sa.BigInteger(), nullable=False))
    
    # Voeg foreign key constraint toe
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_foreign_key('positions_portfolio_id_fkey', 'portfolio', ['portfolio_id'], ['portfolio_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint('positions_portfolio_id_fkey', type_='foreignkey')
        batch_op.drop_column('portfolio_id')

    # ### end Alembic commands ###
